/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/players': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all players */
    get: operations['get_all_players'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/by-email/{email}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get player by email address */
    get: operations['get_player_by_email'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/{player_uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get player by UUID */
    get: operations['get_player_by_uuid'];
    /** Update player team name */
    put: operations['update_player_team_name'];
    post?: never;
    /** Delete player */
    delete: operations['delete_player'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/{player_uuid}/cars': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add car to player */
    post: operations['add_car_to_player'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/{player_uuid}/cars/{car_uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove car from player */
    delete: operations['remove_car_from_player'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/{player_uuid}/pilots': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add pilot to player */
    post: operations['add_pilot_to_player'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/players/{player_uuid}/pilots/{pilot_uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove pilot from player */
    delete: operations['remove_pilot_from_player'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all races */
    get: operations['get_all_races'];
    put?: never;
    /** Create a new race */
    post: operations['create_race'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get race by UUID */
    get: operations['get_race'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/apply-lap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply individual lap action for a player with boost card validation
     * @description This endpoint processes a player's lap action including boost card selection.
     *     The boost card system enforces strategic resource management:
     *     - Players have 5 boost cards (values 0-4) available per cycle
     *     - Each card can only be used once per cycle
     *     - When all 5 cards are used, the hand automatically replenishes
     *     - Boost cards add to performance: `min(base_value, sector.max_value)` + `boost_value`
     *
     *     # Boost Card Usage Flow
     *     1. Player selects an available boost card (0-4)
     *     2. System validates card availability in current cycle
     *     3. Card is marked as used and performance is calculated
     *     4. If all cards used, hand replenishes for next cycle
     *
     *     # Error Handling
     *     - `BOOST_CARD_NOT_AVAILABLE`: Selected card already used in current cycle
     *     - `INVALID_BOOST_VALUE`: Boost value outside 0-4 range
     *     - `CAR_VALIDATION_FAILED`: Invalid car/player combination
     */
    post: operations['apply_lap_action'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/join': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join a race */
    post: operations['join_race'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/pit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Perform a pit stop for a player
     * @description Refills the player's boost card pool (optionally switching tyre) and
     *     consumes the turn as a free boost-0 lap.
     */
    post: operations['pit_stop_action'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/players/{player_uuid}/boost-availability': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get boost card availability for a player in a race
     * @description This endpoint returns the current boost hand state for a player, including:
     *     - Available boost cards (0-4) that can be used
     *     - Complete hand state showing which cards are available/used
     *     - Current cycle information (cycle number, cycles completed)
     *     - Cards remaining before next replenishment
     *     - Next replenishment lap number
     *
     *     The boost hand system manages 5 cards per cycle. When all cards are used,
     *     the hand automatically replenishes for the next cycle. This endpoint helps
     *     the frontend display which boost options are currently available to the player.
     *
     *     # Boost Hand Mechanics
     *     - Each player has 5 boost cards (values 0-4) per cycle
     *     - Cards can only be used once per cycle
     *     - When all 5 cards are used, the hand replenishes automatically
     *     - Next replenishment occurs when `cards_remaining` reaches 0
     */
    get: operations['get_boost_availability'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/players/{player_uuid}/car-data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get complete car data for a player in a race
     * @description This endpoint returns comprehensive car information including:
     *     - Car details (name, UUID)
     *     - Pilot information (skills, performance, class, rarity)
     *     - Engine specifications (straight/curve values, rarity)
     *     - Body specifications (straight/curve values, rarity)
     *
     *     The data is retrieved using the `CarValidationService` which ensures
     *     the car belongs to the player and has all required components.
     */
    get: operations['get_car_data'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/players/{player_uuid}/lap-history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get lap history for a player in a race
     * @description This endpoint returns the player's lap-by-lap performance history for the current race.
     *     It provides:
     *     - Lap records with boost usage, performance values, and movement information
     *     - Boost cycle summaries with aggregated statistics per cycle
     *
     *     The lap history helps players analyze their performance trends and boost card
     *     usage patterns throughout the race. Each lap record includes:
     *     - Lap number and lap characteristic (Straight/Curve)
     *     - Boost card used and which cycle it was from
     *     - Base and final performance values
     *     - Movement information (from/to sectors, movement type)
     *
     *     Cycle summaries provide aggregated statistics:
     *     - Cards used in each cycle
     *     - Laps when cards were used
     *     - Average boost value per cycle
     *
     *     # Note
     *     Historical performance and movement data is currently limited to boost usage tracking.
     *     Full lap-by-lap performance reconstruction would require storing additional historical data.
     */
    get: operations['get_lap_history'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/players/{player_uuid}/local-view': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get local view for a player in a race
     * @description This endpoint calculates and returns the player's 5-sector local view (current sector Â±2).
     *     It provides:
     *     - The player's current sector as the center
     *     - 5 visible sectors with their details (id, name, thresholds, capacity, type)
     *     - All participants within the visible range with their positions
     *     - Current occupancy for each visible sector
     *
     *     The local view handles circular track wrapping automatically, so sectors at the
     *     beginning/end of the track are properly included when the player is near track boundaries.
     *
     *     # Sector Range Calculation
     *     For a player at sector N on a track with M sectors:
     *     - Visible sectors: [N-2, N-1, N, N+1, N+2] (with modulo wrapping)
     *     - Example: Player at sector 1 on 10-sector track sees [9, 0, 1, 2, 3]
     */
    get: operations['get_local_view'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/players/{player_uuid}/performance-preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get performance preview for all boost options
     * @description This endpoint calculates and returns performance predictions for all boost card options (0-4).
     *     It provides:
     *     - Base performance breakdown (engine, body, pilot contributions)
     *     - Sector ceiling application
     *     - Final performance values for each boost option
     *     - Movement probability for each boost option
     *     - Boost cycle information (available cards, cycle status)
     *
     *     The performance calculation follows the additive model used by lap resolution:
     *     `final_value = min(base_value, sector.max_value) + boost_value`
     *
     *     Movement probabilities are determined by comparing final values to sector thresholds:
     *     - `MoveUp`: `final_value` > `sector.max_value`
     *     - Stay: `sector.min_value` <= `final_value` <= `sector.max_value`
     *     - `MoveDown`: `final_value` < `sector.min_value`
     */
    get: operations['get_performance_preview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a player for a race */
    post: operations['register_player'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a race */
    post: operations['start_race'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get race status */
    get: operations['get_race_status'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/status-detailed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get detailed race status with comprehensive boost hand information
     * @description This endpoint provides complete race status including boost card system state.
     *     When `player_uuid` is provided, returns player-specific data including:
     *     - Current boost hand state (available/used cards)
     *     - Boost cycle information (current cycle, cycles completed)
     *     - Boost usage history and cycle summaries
     *     - Performance impact preview for each boost card
     *
     *     # Boost Hand State Information
     *     - `available_cards`: List of boost card values (0-4) currently available
     *     - `hand_state`: Detailed boolean map of each card's availability
     *     - `current_cycle`: Current boost cycle number (starts at 1)
     *     - `cycles_completed`: Number of complete cycles finished
     *     - `cards_remaining`: Cards left before next replenishment
     *     - `boost_impact_preview`: Performance prediction for each boost option
     *
     *     # Usage History
     *     - `boost_usage_history`: Lap-by-lap record of boost card usage
     *     - `boost_cycle_summaries`: Aggregated statistics per cycle
     */
    get: operations['get_race_status_detailed'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/turn': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Process a turn in the race */
    post: operations['process_turn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/races/{race_uuid}/turn-phase': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get turn phase information for a race
     * @description This endpoint returns the current turn phase state for simultaneous turn resolution.
     *     It provides information about:
     *     - Current turn phase (`WaitingForPlayers`, `AllSubmitted`, Processing, Complete)
     *     - Current lap number and lap characteristic
     *     - List of players who have submitted actions
     *     - List of players who are still pending action submission
     *     - Total number of active players
     *
     *     Turn phases are determined by:
     *     - Complete: Race status is not `InProgress`
     *     - `AllSubmitted`: All active participants have submitted actions
     *     - `WaitingForPlayers`: Some participants haven't submitted actions yet
     */
    get: operations['get_turn_phase'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login user */
    post: operations['login_user'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations['register_user'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health_check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check endpoint */
    get: operations['health_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/races/{race_uuid}/submit-action': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a single player's turn action (boost selection)
     * @description This endpoint allows individual players to submit their boost selection for the current turn.
     *     Unlike the batch `process_turn` endpoint, this handles one player at a time and stores
     *     the action until all players have submitted their choices.
     */
    post: operations['submit_turn_action'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddCarRequest: {
      name: string;
    };
    AddPilotRequest: {
      name: string;
      pilot_class: components['schemas']['PilotClass'];
      rarity: components['schemas']['PilotRarity'];
      skills: components['schemas']['PilotSkillsRequest'];
    };
    /**
     * @description Request to apply a lap action with boost card selection
     *
     *     # Boost Card System
     *     The `boost_value` field represents which boost card to use (0-4).
     *     Each player has 5 boost cards per cycle that can be used once each.
     *     When all cards are used, the hand automatically replenishes.
     *
     *     # Performance Calculation
     *     Final performance = `min(base_performance, sector.max_value)` + `boost_value`
     *     (additive model, matching lap resolution). `boost_value` ranges 0-4.
     */
    ApplyLapRequest: {
      /**
       * Format: int32
       * @description Boost card value to use (0-4). Must be available in current cycle.
       * @example 3
       */
      boost_value: number;
      /**
       * @description UUID of the car being used for this lap
       * @example 550e8400-e29b-41d4-a716-446655440001
       */
      car_uuid: string;
      /**
       * @description UUID of the player making the lap action
       * @example 550e8400-e29b-41d4-a716-446655440000
       */
      player_uuid: string;
    };
    BasePerformance: {
      /** Format: int32 */
      base_value: number;
      /** Format: int32 */
      body_contribution: number;
      /** Format: int32 */
      capped_base_value: number;
      /** Format: int32 */
      engine_contribution: number;
      lap_characteristic: string;
      /** Format: int32 */
      pilot_contribution: number;
      /** Format: int32 */
      sector_ceiling: number;
    };
    Body: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      curve_value: number;
      name: components['schemas']['BodyName'];
      rarity: components['schemas']['ComponentRarity'];
      /** Format: int32 */
      straight_value: number;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    BodyInfo: {
      /** Format: int32 */
      curve_value: number;
      name: string;
      rarity: string;
      /** Format: int32 */
      straight_value: number;
      uuid: string;
    };
    BodyName: string;
    /** @description Boost availability information for API responses */
    BoostAvailability: {
      /**
       * Format: binary
       * @description Available boost card values (always includes 0, the free no-boost move)
       */
      available_cards: string;
      /** @description Performance preview for available cards only */
      boost_impact_preview: components['schemas']['BoostImpactOption'][];
      /** Format: int32 */
      cards_remaining: number;
      /**
       * @description Remaining count per boost card value (keys "1".."4")
       *     Using String keys for `MongoDB` compatibility
       */
      hand_state: {
        [key: string]: number;
      };
      /** Format: int32 */
      pit_stops_completed: number;
      tyre_type: components['schemas']['TyreType'];
    };
    BoostAvailabilityResponse: {
      /** Format: binary */
      available_cards: string;
      /** Format: int32 */
      cards_remaining: number;
      /** @description Remaining count per boost card value (keys "1".."4"). */
      hand_state: {
        [key: string]: number;
      };
      /** Format: int32 */
      pit_stops_completed: number;
      tyre_type: components['schemas']['TyreType'];
    };
    /** @description Error types for boost card operations */
    BoostCardError:
      | {
          /** Format: int32 */
          details: number;
          /** @enum {string} */
          error_type: 'InvalidBoostValue';
        }
      | {
          details: {
            /** Format: binary */
            available_cards: string;
            /** Format: int32 */
            boost_value: number;
          };
          /** @enum {string} */
          error_type: 'CardNotAvailable';
        };
    /** @description Error response struct with available cards information */
    BoostCardErrorResponse: {
      /** Format: binary */
      available_cards: string;
      /** Format: int32 */
      cards_remaining: number;
      error_code: string;
      message: string;
      /** Format: int32 */
      pit_stops_completed: number;
    };
    BoostCycleInfo: {
      /** Format: binary */
      available_cards: string;
      /** Format: int32 */
      cards_remaining: number;
      /** Format: int32 */
      pit_stops_completed: number;
      tyre_type: components['schemas']['TyreType'];
    };
    /**
     * @description Summary statistics for a complete boost cycle
     *     Provides cycle-level analytics for strategic analysis
     */
    BoostCycleSummary: {
      /**
       * Format: float
       * @description Average boost value for this cycle
       */
      average_boost: number;
      /**
       * Format: binary
       * @description Boost card values used in this cycle (in order)
       */
      cards_used: string;
      /**
       * Format: int32
       * @description Cycle number
       */
      cycle_number: number;
      /** @description Lap numbers when cards were used in this cycle */
      laps_in_cycle: number[];
    };
    /**
     * @description Boost hand management system for tracking available boost cards.
     *
     *     Cards are a multiset of values 1-4 drawn from the chosen [`TyreType`]'s pool.
     *     Boost value 0 is NOT a card: it is the always-available free no-boost move.
     *     The hand does NOT auto-replenish; a pit stop ([`BoostHand::refill`]) is the
     *     only way to restore cards (and may swap tyre).
     */
    BoostHand: {
      /**
       * @description Remaining count for each boost card value.
       *     Keys are values `"1".."4"` (value 0 is never a card).
       *     Using String keys for `MongoDB` compatibility.
       */
      cards: {
        [key: string]: number;
      };
      /**
       * Format: int32
       * @description Number of cards remaining (sum of all counts).
       */
      cards_remaining: number;
      /**
       * Format: int32
       * @description Total number of pit stops completed (each refills the pool).
       */
      pit_stops_completed?: number;
      tyre_type?: components['schemas']['TyreType'];
    };
    /** @description Boost impact option with availability flag */
    BoostImpactOption: {
      /** Format: int32 */
      boost_value: number;
      is_available: boolean;
      movement_probability: components['schemas']['MovementProbability'];
      /** Format: int32 */
      predicted_final_value: number;
    };
    BoostOption: {
      /** Format: int32 */
      boost_value: number;
      /** Format: int32 */
      final_value: number;
      is_available: boolean;
      movement_probability: string;
    };
    /**
     * @description Record of a single boost card usage
     *     Tracks lap-by-lap boost card usage for history and analytics
     */
    BoostUsageRecord: {
      /**
       * Format: int32
       * @description Boost card value that was used (0-4)
       */
      boost_value: number;
      /**
       * Format: int32
       * @description Number of cards remaining after this usage
       */
      cards_remaining_after: number;
      /**
       * Format: int32
       * @description Cycle number when the boost was used
       */
      cycle_number: number;
      /**
       * Format: int32
       * @description Lap number when the boost was used
       */
      lap_number: number;
      /** @description Whether replenishment occurred after this usage */
      replenishment_occurred: boolean;
    };
    /** @description Result of using a boost card */
    BoostUsageResult: {
      /** Format: int32 */
      boost_value: number;
      /** Format: int32 */
      cards_remaining: number;
      /** Format: int32 */
      pit_stops_completed: number;
    };
    Car: {
      /** Format: uuid */
      body_uuid?: string | null;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      engine_uuid?: string | null;
      is_equipped: boolean;
      name: components['schemas']['CarName'];
      pilot_uuids: string[];
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    CarDataResponse: {
      body: components['schemas']['BodyInfo'];
      car: components['schemas']['CarInfo'];
      engine: components['schemas']['EngineInfo'];
      pilot: components['schemas']['PilotInfo'];
    };
    CarInfo: {
      name: string;
      uuid: string;
    };
    CarName: string;
    /** @enum {string} */
    ComponentRarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';
    CreateRaceRequest: {
      name: string;
      sectors: components['schemas']['CreateSectorRequest'][];
      /** Format: int32 */
      total_laps: number;
      track_name: string;
      /**
       * Format: int32
       * @description Per-turn submission timeout in seconds for multiplayer races.
       *     Defaults to 60 when omitted; valid range 5-600.
       */
      turn_timeout_secs?: number | null;
    };
    CreateSectorRequest: {
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      max_value: number;
      /** Format: int32 */
      min_value: number;
      name: string;
      sector_type: components['schemas']['SectorType'];
      /** Format: int32 */
      slot_capacity?: number | null;
    };
    CurrentPlayerPosition: {
      /** Format: int32 */
      current_sector: number;
      /** Format: int32 */
      distance_to_leader: number;
      /** Format: int32 */
      overall_rank: number;
      /** Format: int32 */
      position_in_sector: number;
      /** Format: int32 */
      sector_rank: number;
    };
    CycleSummary: {
      /** Format: float */
      average_boost: number;
      /** Format: binary */
      cards_used: string;
      /** Format: int32 */
      cycle_number: number;
      laps_in_cycle: number[];
    };
    DetailedRaceStatusResponse: {
      player_data?: components['schemas']['PlayerSpecificData'] | null;
      race_metadata: components['schemas']['RaceMetadata'];
      race_progress: components['schemas']['RaceProgressStatus'];
      track_situation: components['schemas']['TrackSituationData'];
    };
    Email: string;
    Engine: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      curve_value: number;
      name: components['schemas']['EngineName'];
      rarity: components['schemas']['ComponentRarity'];
      /** Format: int32 */
      straight_value: number;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    EngineInfo: {
      /** Format: int32 */
      curve_value: number;
      name: string;
      rarity: string;
      /** Format: int32 */
      straight_value: number;
      uuid: string;
    };
    EngineName: string;
    /**
     * @description Standard error response format used across all endpoints
     *
     *     This struct provides a consistent error response format with:
     *     - error: A short error code or category
     *     - message: A human-readable error message
     *     - details: Optional additional information about the error
     */
    ErrorResponse: {
      details?: string | null;
      error: string;
      message: string;
    };
    /** @description A hashed password stored in the database */
    HashedPassword: string;
    HealthResponse: {
      message: string;
      status: string;
    };
    JoinRaceRequest: {
      car_uuid: string;
      pilot_uuid: string;
      player_uuid: string;
    };
    LapAction: {
      /** Format: int32 */
      boost_value: number;
      /** Format: uuid */
      player_uuid: string;
    };
    LapActionRequest: {
      /** Format: int32 */
      boost_value: number;
      player_uuid: string;
    };
    /** @enum {string} */
    LapCharacteristic: 'Straight' | 'Curve';
    LapHistoryResponse: {
      cycle_summaries: components['schemas']['CycleSummary'][];
      laps: components['schemas']['LapRecord'][];
    };
    LapPerformanceRecord: {
      /** Format: int32 */
      boost_used: number;
      /** Format: int32 */
      final_value: number;
      /** Format: int32 */
      from_sector: number;
      /** Format: int32 */
      lap_number: number;
      movement_type: components['schemas']['MovementType'];
      /** Format: int32 */
      to_sector: number;
    };
    LapRecord: {
      /** Format: int32 */
      base_value: number;
      /** Format: int32 */
      boost_cycle: number;
      /** Format: int32 */
      boost_used: number;
      /** Format: int32 */
      final_value: number;
      /** Format: int32 */
      from_sector: number;
      lap_characteristic: string;
      /** Format: int32 */
      lap_number: number;
      movement_type: string;
      /** Format: int32 */
      to_sector: number;
    };
    LapResult: {
      /** Format: int32 */
      lap: number;
      lap_characteristic: components['schemas']['LapCharacteristic'];
      movements: components['schemas']['ParticipantMovement'][];
      sector_positions: {
        [key: string]: components['schemas']['RaceParticipant'][];
      };
    };
    LapResultResponse: {
      race_status: components['schemas']['RaceStatus'];
      result: components['schemas']['LapResult'];
    };
    LeaderboardEntry: {
      car_name: string;
      /** Format: int32 */
      current_lap: number;
      /** Format: int32 */
      current_sector: number;
      /** Format: int32 */
      overall_rank: number;
      player_name?: string | null;
      player_uuid: string;
      /** Format: int32 */
      position_in_sector: number;
      /** Format: int32 */
      total_value: number;
    };
    LocalViewResponse: {
      /** Format: int32 */
      center_sector: number;
      /**
       * Format: int32
       * @description Total number of sectors on the track. Lets the UI number sectors with
       *     the leading (highest-index) sector as "Sector 1".
       */
      total_sectors: number;
      visible_participants: components['schemas']['ParticipantInfo'][];
      visible_sectors: components['schemas']['SectorInfo'][];
    };
    /**
     * @description Movement probability based on performance prediction
     * @enum {string}
     */
    MovementProbability: 'MoveUp' | 'Stay' | 'MoveDown';
    /** @enum {string} */
    MovementType: 'StayedInSector' | 'MovedUp' | 'MovedDown' | 'FinishedLap' | 'FinishedRace';
    ParticipantInfo: {
      car_name: string;
      /** Format: int32 */
      current_lap: number;
      /** Format: int32 */
      current_sector: number;
      is_finished: boolean;
      player_name?: string | null;
      player_uuid: string;
      /** Format: int32 */
      position_in_sector: number;
      /** Format: int32 */
      total_value: number;
    };
    ParticipantMovement: {
      /** Format: int32 */
      from_sector: number;
      movement_type: components['schemas']['MovementType'];
      player_uuid: string;
      /** Format: int32 */
      to_sector: number;
    };
    /** @description Detailed performance calculation breakdown */
    PerformanceCalculation: {
      /** Format: int32 */
      base_value: number;
      /** Format: int32 */
      body_contribution: number;
      /** Format: int32 */
      boost_value: number;
      /** Format: int32 */
      capped_base_value: number;
      /** Format: int32 */
      engine_contribution: number;
      /** Format: int32 */
      final_value: number;
      /** Format: int32 */
      pilot_contribution: number;
      /** Format: int32 */
      sector_ceiling: number;
    };
    PerformancePreview: {
      /** Format: int32 */
      base_value: number;
      /** Format: int32 */
      body_contribution: number;
      /** Format: int32 */
      capped_base_value: number;
      /** Format: int32 */
      engine_contribution: number;
      /** Format: int32 */
      pilot_contribution: number;
      /** Format: int32 */
      sector_ceiling: number;
    };
    PerformancePreviewResponse: {
      base_performance: components['schemas']['BasePerformance'];
      boost_cycle_info: components['schemas']['BoostCycleInfo'];
      boost_options: components['schemas']['BoostOption'][];
    };
    PerformanceThresholds: {
      /** Format: int32 */
      max_value: number;
      /** Format: int32 */
      min_value: number;
      /** Format: int32 */
      move_down_threshold: number;
      /** Format: int32 */
      move_up_threshold: number;
    };
    Pilot: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      experience_level: number;
      is_active: boolean;
      name: components['schemas']['PilotName'];
      performance: components['schemas']['PilotPerformance'];
      pilot_class: components['schemas']['PilotClass'];
      rarity: components['schemas']['PilotRarity'];
      skills: components['schemas']['PilotSkills'];
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    /** @enum {string} */
    PilotClass: 'Speedster' | 'Technician' | 'Endurance' | 'AllRounder';
    PilotClassBonus: {
      /** Format: int32 */
      acceleration_bonus: number;
      /** Format: int32 */
      durability_bonus: number;
      /** Format: int32 */
      handling_bonus: number;
      /** Format: int32 */
      speed_bonus: number;
    };
    PilotInfo: {
      name: string;
      performance: components['schemas']['PilotPerformance'];
      pilot_class: string;
      rarity: string;
      skills: components['schemas']['PilotSkills'];
      uuid: string;
    };
    PilotName: string;
    PilotPerformance: {
      /** Format: int32 */
      curve_value: number;
      /** Format: int32 */
      straight_value: number;
    };
    /** @enum {string} */
    PilotRarity: 'Rookie' | 'Professional' | 'Expert' | 'Champion' | 'Legend';
    PilotSkills: {
      /** Format: int32 */
      focus: number;
      /** Format: int32 */
      precision: number;
      /** Format: int32 */
      reaction_time: number;
      /** Format: int32 */
      stamina: number;
    };
    PilotSkillsRequest: {
      /** Format: int32 */
      focus: number;
      /** Format: int32 */
      precision: number;
      /** Format: int32 */
      reaction_time: number;
      /** Format: int32 */
      stamina: number;
    };
    /**
     * @description Request to perform a pit stop.
     *
     *     A pit stop refills the player's boost card pool and consumes the turn as a
     *     free boost-0 lap. Optionally switches to a new tyre type (which defines the
     *     refilled pool); if omitted, the current tyre is kept.
     */
    PitStopRequest: {
      /** @description UUID of the car being used */
      car_uuid: string;
      new_tyre?: components['schemas']['TyreType'] | null;
      /** @description UUID of the player pitting */
      player_uuid: string;
    };
    Player: {
      _id?: string | null;
      bodies: components['schemas']['Body'][];
      cars: components['schemas']['Car'][];
      /** Format: date-time */
      created_at: string;
      email: components['schemas']['Email'];
      engines: components['schemas']['Engine'][];
      password_hash: components['schemas']['HashedPassword'];
      pilots: components['schemas']['Pilot'][];
      role: components['schemas']['UserRole'];
      team_name: components['schemas']['TeamName'];
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    PlayerRacePosition: {
      /** Format: int32 */
      position_in_sector: number;
      /** Format: int32 */
      qualification_rank: number;
      /** Format: int32 */
      starting_sector: number;
    };
    PlayerResponse: {
      message: string;
      player: components['schemas']['Player'];
    };
    PlayerSpecificData: {
      boost_availability: components['schemas']['BoostAvailability'];
      boost_cycle_summaries: components['schemas']['BoostCycleSummary'][];
      boost_usage_history: components['schemas']['BoostUsageRecord'][];
      current_position: components['schemas']['CurrentPlayerPosition'];
      lap_history?: components['schemas']['LapPerformanceRecord'][] | null;
      performance_preview: components['schemas']['PerformancePreview'];
    };
    ProcessLapRequest: {
      actions: components['schemas']['LapActionRequest'][];
    };
    Race: {
      _id?: string | null;
      action_submissions: {
        [key: string]: number;
      };
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      current_lap: number;
      lap_characteristic: components['schemas']['LapCharacteristic'];
      name: string;
      participants: components['schemas']['RaceParticipant'][];
      pending_actions: components['schemas']['LapAction'][];
      pending_performance_calculations: {
        [key: string]: components['schemas']['PerformanceCalculation'];
      };
      status: components['schemas']['RaceStatus'];
      /** Format: int32 */
      total_laps: number;
      track: components['schemas']['Track'];
      /**
       * Format: int64
       * @description Armed deadline for the current turn (Unix seconds); `None` = not armed.
       */
      turn_deadline?: number | null;
      /**
       * Format: int32
       * @description Per-turn submission timeout in seconds; `None` = no timer (solo races).
       */
      turn_timeout_secs?: number | null;
      /**
       * Format: int32
       * @description Number of processing turns taken so far. Used only as a safety bound to
       *     guarantee a race terminates even on an unwinnable track.
       */
      turns_taken?: number;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      uuid: string;
    };
    RaceMetadata: {
      /** Format: date-time */
      estimated_completion?: string | null;
      race_name: string;
      race_uuid: string;
      /** Format: date-time */
      start_time?: string | null;
      /** Format: int32 */
      total_turns: number;
      track_name: string;
    };
    RaceParticipant: {
      boost_hand: components['schemas']['BoostHand'];
      /** @description History of boost card usage for this participant */
      boost_usage_history?: components['schemas']['BoostUsageRecord'][];
      /** Format: uuid */
      car_uuid: string;
      /** Format: int32 */
      current_lap: number;
      /** Format: int32 */
      current_position_in_sector: number;
      /** Format: int32 */
      current_sector: number;
      /** Format: int32 */
      finish_position?: number | null;
      /**
       * @description Whether this participant is controlled by the AI (solo mode opponents).
       *     Defaults to `false` so existing/serialized races deserialize as human.
       */
      is_ai?: boolean;
      is_finished: boolean;
      /** Format: uuid */
      pilot_uuid: string;
      /** Format: uuid */
      player_uuid: string;
      /** Format: int32 */
      total_value: number;
    };
    RaceProgressStatus: {
      /** Format: int32 */
      current_lap: number;
      /** Format: int32 */
      finished_participants: number;
      lap_characteristic: components['schemas']['LapCharacteristic'];
      /** Format: int32 */
      participants_count: number;
      status: components['schemas']['RaceStatusType'];
      /** Format: int32 */
      total_laps: number;
      turn_phase: components['schemas']['TurnPhase'];
    };
    RaceResponse: {
      message: string;
      race: components['schemas']['Race'];
    };
    /** @enum {string} */
    RaceStatus: 'Waiting' | 'InProgress' | 'Finished' | 'Cancelled';
    RaceStatusType:
      | 'Waiting'
      | 'Ongoing'
      | 'Finished'
      | {
          Error: {
            message: string;
          };
        };
    RegisterPlayerRequest: {
      car_uuid: string;
      player_uuid: string;
      tyre_type?: components['schemas']['TyreType'];
    };
    RegisterPlayerResponse: {
      message: string;
      player_position: components['schemas']['PlayerRacePosition'];
      race_status: components['schemas']['RaceProgressStatus'];
      success: boolean;
    };
    Sector: {
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      max_value: number;
      /** Format: int32 */
      min_value: number;
      name: string;
      sector_type: components['schemas']['SectorType'];
      /** Format: int32 */
      slot_capacity?: number | null;
    };
    SectorCapacityInfo: {
      /** Format: int32 */
      available_slots?: number | null;
      /** Format: int32 */
      current_occupancy: number;
      /** Format: int32 */
      max_capacity?: number | null;
    };
    SectorInfo: {
      /** Format: int32 */
      current_occupancy: number;
      /** Format: int32 */
      id: number;
      /** Format: int32 */
      max_value: number;
      /** Format: int32 */
      min_value: number;
      name: string;
      sector_type: string;
      /** Format: int32 */
      slot_capacity?: number | null;
    };
    SectorParticipant: {
      car_name: string;
      /** Format: int32 */
      current_lap: number;
      is_finished: boolean;
      player_name?: string | null;
      player_uuid: string;
      /** Format: int32 */
      position_in_sector: number;
      /** Format: int32 */
      total_value: number;
    };
    SectorSituation: {
      capacity_info: components['schemas']['SectorCapacityInfo'];
      participants: components['schemas']['SectorParticipant'][];
      performance_thresholds: components['schemas']['PerformanceThresholds'];
      /** Format: int32 */
      sector_id: number;
      sector_name: string;
      sector_type: components['schemas']['SectorType'];
    };
    /** @enum {string} */
    SectorType: 'Start' | 'Straight' | 'Curve' | 'Finish';
    /** @description Request to submit a single player's turn action */
    SubmitTurnActionRequest: {
      /** Format: int32 */
      boost_value: number;
      player_uuid: string;
    };
    /** @description Response after submitting a turn action */
    SubmitTurnActionResponse: {
      message: string;
      /** Format: int32 */
      players_submitted: number;
      success: boolean;
      /** Format: int32 */
      total_players: number;
      turn_phase: string;
      /**
       * Format: int32
       * @description Turn counter after this submission — the client's baseline for
       *     detecting that the turn it is waiting on has executed.
       */
      turns_taken: number;
    };
    TeamName: string;
    Track: {
      name: string;
      sectors: components['schemas']['Sector'][];
      /** Format: uuid */
      uuid: string;
    };
    TrackSituationData: {
      lap_leaderboard: components['schemas']['LeaderboardEntry'][];
      recent_movements: components['schemas']['ParticipantMovement'][];
      sectors: components['schemas']['SectorSituation'][];
    };
    /** @enum {string} */
    TurnPhase: 'WaitingForPlayers' | 'AllSubmitted' | 'Processing' | 'TurnProcessed' | 'Complete';
    TurnPhaseResponse: {
      /** Format: int32 */
      current_lap: number;
      lap_characteristic: string;
      pending_players: string[];
      /**
       * Format: int64
       * @description Server-computed seconds until the deadline, clamped to >= 0; `null`
       *     whenever `turn_deadline` is. Drives the client countdown without
       *     trusting client clocks.
       */
      seconds_remaining?: number | null;
      submitted_players: string[];
      /** Format: int32 */
      total_active_players: number;
      /** Format: int32 */
      total_laps: number;
      /**
       * Format: int64
       * @description Armed submission deadline for the current turn (Unix epoch seconds);
       *     `null` for solo races or when no timeout is configured.
       */
      turn_deadline?: number | null;
      turn_phase: string;
      /**
       * Format: int32
       * @description Turn counter — increments exactly once per processed turn. Clients
       *     detect "the turn I was waiting on executed" by this exceeding the
       *     baseline captured at submission (`current_lap` saturates at
       *     `total_laps` and cannot signal the final turn).
       */
      turns_taken: number;
    };
    /**
     * @description Tyre type chosen at race entry (and at each pit stop). It determines the
     *     boost card pool: softer tyres give fewer but stronger cards, harder tyres
     *     give more but weaker cards.
     * @enum {string}
     */
    TyreType: 'Soft' | 'Medium' | 'Hard';
    UpdateTeamNameRequest: {
      team_name: string;
    };
    /** @description User credentials for authentication */
    UserCredentials: {
      email: string;
      password: string;
    };
    /** @description Registration data for new users */
    UserRegistration: {
      email: string;
      password: string;
      team_name: string;
    };
    /**
     * @description User roles for authorization
     * @enum {string}
     */
    UserRole: 'Player' | 'Admin' | 'SuperAdmin';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_all_players: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all players */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Player'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_player_by_email: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's email address */
        email: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Player found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Player'];
        };
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_player_by_uuid: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Player found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Player'];
        };
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_player_team_name: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTeamNameRequest'];
      };
    };
    responses: {
      /** @description Team name updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Player deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  add_car_to_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddCarRequest'];
      };
    };
    responses: {
      /** @description Car added successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  remove_car_from_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
        /** @description Car UUID to remove */
        car_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Car removed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player or car not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  add_pilot_to_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddPilotRequest'];
      };
    };
    responses: {
      /** @description Pilot added successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  remove_pilot_from_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Player's UUID */
        player_uuid: string;
        /** @description Pilot UUID to remove */
        pilot_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pilot removed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlayerResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Player or pilot not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_all_races: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all races */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Race'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_race: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRaceRequest'];
      };
    };
    responses: {
      /** @description Race created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RaceResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_race: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Race found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Race'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  apply_lap_action: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    /** @description Lap action request with boost card selection */
    requestBody: {
      content: {
        /**
         * @example {
         *       "player_uuid": "550e8400-e29b-41d4-a716-446655440000",
         *       "car_uuid": "550e8400-e29b-41d4-a716-446655440001",
         *       "boost_value": 3
         *     }
         */
        'application/json': components['schemas']['ApplyLapRequest'];
      };
    };
    responses: {
      /** @description Lap action processed successfully. Returns updated race status with boost hand state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "race_progress": {
           *         "status": "Ongoing",
           *         "current_lap": 2,
           *         "total_laps": 5,
           *         "participants_count": 4,
           *         "finished_participants": 0
           *       },
           *       "player_data": {
           *         "boost_availability": {
           *           "available_cards": [
           *             0,
           *             1,
           *             2,
           *             4
           *           ],
           *           "hand_state": {
           *             "0": true,
           *             "1": true,
           *             "2": true,
           *             "3": false,
           *             "4": true
           *           },
           *           "current_cycle": 1,
           *           "cycles_completed": 0,
           *           "cards_remaining": 4,
           *           "next_replenishment_at": 4
           *         }
           *       }
           *     }
           */
          'application/json': components['schemas']['DetailedRaceStatusResponse'];
        };
      };
      /** @description Boost card validation error or invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoostCardErrorResponse'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot process action (race not in progress, etc.) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  join_race: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinRaceRequest'];
      };
    };
    responses: {
      /** @description Successfully joined race */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RaceResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot join race */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  pit_stop_action: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PitStopRequest'];
      };
    };
    responses: {
      /** @description Pit stop applied */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DetailedRaceStatusResponse'];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoostCardErrorResponse'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoostCardErrorResponse'];
        };
      };
      /** @description Invalid race state */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BoostCardErrorResponse'];
        };
      };
    };
  };
  get_boost_availability: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
        /** @description Player UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Boost availability retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "available_cards": [
           *         1,
           *         2,
           *         4
           *       ],
           *       "hand_state": {
           *         "0": false,
           *         "1": true,
           *         "2": true,
           *         "3": false,
           *         "4": true
           *       },
           *       "current_cycle": 1,
           *       "cycles_completed": 0,
           *       "cards_remaining": 3,
           *       "next_replenishment_at": 3
           *     }
           */
          'application/json': components['schemas']['BoostAvailabilityResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Player not found in race or race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_NOT_FOUND",
           *       "message": "Player not found in race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Race not in progress or player already finished */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_FINISHED",
           *       "message": "Player has already finished the race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_car_data: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
        /** @description Player UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Car data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "car": {
           *         "uuid": "550e8400-e29b-41d4-a716-446655440001",
           *         "name": "Lightning Bolt"
           *       },
           *       "pilot": {
           *         "uuid": "550e8400-e29b-41d4-a716-446655440002",
           *         "name": "Max Speed",
           *         "pilot_class": "SpeedDemon",
           *         "rarity": "Professional",
           *         "skills": {
           *           "reaction_time": 8,
           *           "precision": 7,
           *           "focus": 6,
           *           "stamina": 7
           *         },
           *         "performance": {
           *           "straight_value": 5,
           *           "curve_value": 4
           *         }
           *       },
           *       "engine": {
           *         "uuid": "550e8400-e29b-41d4-a716-446655440003",
           *         "name": "V8 Turbo",
           *         "rarity": "Rare",
           *         "straight_value": 8,
           *         "curve_value": 6
           *       },
           *       "body": {
           *         "uuid": "550e8400-e29b-41d4-a716-446655440004",
           *         "name": "Aerodynamic Frame",
           *         "rarity": "Rare",
           *         "straight_value": 7,
           *         "curve_value": 8
           *       }
           *     }
           */
          'application/json': components['schemas']['CarDataResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Player not found in race */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_NOT_FOUND",
           *       "message": "Player not found in race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_lap_history: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
        /** @description Player UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lap history retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "laps": [
           *         {
           *           "lap_number": 1,
           *           "lap_characteristic": "Straight",
           *           "boost_used": 2,
           *           "boost_cycle": 1,
           *           "base_value": 20,
           *           "final_value": 23,
           *           "from_sector": 0,
           *           "to_sector": 3,
           *           "movement_type": "MovedUp"
           *         },
           *         {
           *           "lap_number": 2,
           *           "lap_characteristic": "Curve",
           *           "boost_used": 0,
           *           "boost_cycle": 1,
           *           "base_value": 18,
           *           "final_value": 18,
           *           "from_sector": 3,
           *           "to_sector": 4,
           *           "movement_type": "StayedInSector"
           *         }
           *       ],
           *       "cycle_summaries": [
           *         {
           *           "cycle_number": 1,
           *           "cards_used": [
           *             2,
           *             0,
           *             3
           *           ],
           *           "laps_in_cycle": [
           *             1,
           *             2,
           *             3
           *           ],
           *           "average_boost": 1.67
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['LapHistoryResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Player not found in race or race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_NOT_FOUND",
           *       "message": "Player not found in race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_local_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
        /** @description Player UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Local view calculated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "center_sector": 5,
           *       "visible_sectors": [
           *         {
           *           "id": 3,
           *           "name": "Sector 3",
           *           "min_value": 15,
           *           "max_value": 25,
           *           "slot_capacity": 3,
           *           "sector_type": "Normal",
           *           "current_occupancy": 1
           *         },
           *         {
           *           "id": 4,
           *           "name": "Sector 4",
           *           "min_value": 20,
           *           "max_value": 30,
           *           "slot_capacity": 3,
           *           "sector_type": "Normal",
           *           "current_occupancy": 2
           *         },
           *         {
           *           "id": 5,
           *           "name": "Sector 5",
           *           "min_value": 25,
           *           "max_value": 35,
           *           "slot_capacity": 3,
           *           "sector_type": "Normal",
           *           "current_occupancy": 1
           *         },
           *         {
           *           "id": 6,
           *           "name": "Sector 6",
           *           "min_value": 30,
           *           "max_value": 40,
           *           "slot_capacity": 3,
           *           "sector_type": "Normal",
           *           "current_occupancy": 0
           *         },
           *         {
           *           "id": 7,
           *           "name": "Sector 7",
           *           "min_value": 35,
           *           "max_value": 45,
           *           "slot_capacity": 3,
           *           "sector_type": "Normal",
           *           "current_occupancy": 1
           *         }
           *       ],
           *       "visible_participants": [
           *         {
           *           "player_uuid": "550e8400-e29b-41d4-a716-446655440000",
           *           "player_name": "Player 1",
           *           "car_name": "Lightning Bolt",
           *           "current_sector": 5,
           *           "position_in_sector": 1,
           *           "total_value": 45,
           *           "current_lap": 2,
           *           "is_finished": false
           *         },
           *         {
           *           "player_uuid": "550e8400-e29b-41d4-a716-446655440001",
           *           "player_name": "Player 2",
           *           "car_name": "Thunder Strike",
           *           "current_sector": 4,
           *           "position_in_sector": 1,
           *           "total_value": 42,
           *           "current_lap": 2,
           *           "is_finished": false
           *         }
           *       ]
           *     }
           */
          'application/json': components['schemas']['LocalViewResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Player not found in race or race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_NOT_FOUND",
           *       "message": "Player not found in race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_performance_preview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
        /** @description Player UUID */
        player_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Performance preview calculated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "base_performance": {
           *         "engine_contribution": 8,
           *         "body_contribution": 7,
           *         "pilot_contribution": 5,
           *         "base_value": 20,
           *         "sector_ceiling": 25,
           *         "capped_base_value": 20,
           *         "lap_characteristic": "Straight"
           *       },
           *       "boost_options": [
           *         {
           *           "boost_value": 0,
           *           "is_available": false,
           *           "final_value": 20,
           *           "movement_probability": "Stay"
           *         },
           *         {
           *           "boost_value": 1,
           *           "is_available": true,
           *           "final_value": 22,
           *           "movement_probability": "Stay"
           *         },
           *         {
           *           "boost_value": 2,
           *           "is_available": true,
           *           "final_value": 23,
           *           "movement_probability": "Stay"
           *         },
           *         {
           *           "boost_value": 3,
           *           "is_available": true,
           *           "final_value": 25,
           *           "movement_probability": "MoveUp"
           *         },
           *         {
           *           "boost_value": 4,
           *           "is_available": true,
           *           "final_value": 26,
           *           "movement_probability": "MoveUp"
           *         }
           *       ],
           *       "boost_cycle_info": {
           *         "current_cycle": 1,
           *         "cycles_completed": 0,
           *         "cards_remaining": 4,
           *         "available_cards": [
           *           1,
           *           2,
           *           3,
           *           4
           *         ]
           *       }
           *     }
           */
          'application/json': components['schemas']['PerformancePreviewResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Player not found in race or race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "PLAYER_NOT_FOUND",
           *       "message": "Player not found in race",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Race not in progress or player already finished */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "RACE_NOT_IN_PROGRESS",
           *       "message": "Race is not in progress",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  register_player: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterPlayerRequest'];
      };
    };
    responses: {
      /** @description Successfully registered for race */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegisterPlayerResponse'];
        };
      };
      /** @description Invalid request or car validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot register (race started, player already registered, etc.) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  start_race: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Race started successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RaceResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot start race */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_race_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Race status */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RaceStatus'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_race_status_detailed: {
    parameters: {
      query?: {
        /** @description Player UUID for player-specific boost hand data */
        player_uuid?: string | null;
        /** @description Include detailed lap and boost usage history */
        include_history?: boolean | null;
      };
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Detailed race status with boost hand information */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "race_progress": {
           *         "status": "Ongoing",
           *         "current_lap": 3,
           *         "total_laps": 5,
           *         "participants_count": 2,
           *         "finished_participants": 0
           *       },
           *       "track_situation": {
           *         "sectors": [
           *           {
           *             "sector_id": 1,
           *             "sector_name": "Start/Finish",
           *             "participants": [
           *               {
           *                 "player_uuid": "550e8400-e29b-41d4-a716-446655440000",
           *                 "position_in_sector": 1,
           *                 "total_value": 45,
           *                 "current_lap": 3
           *               }
           *             ]
           *           }
           *         ]
           *       },
           *       "player_data": {
           *         "boost_availability": {
           *           "available_cards": [
           *             1,
           *             4
           *           ],
           *           "hand_state": {
           *             "0": false,
           *             "1": true,
           *             "2": false,
           *             "3": false,
           *             "4": true
           *           },
           *           "current_cycle": 1,
           *           "cycles_completed": 0,
           *           "cards_remaining": 2,
           *           "next_replenishment_at": 2,
           *           "boost_impact_preview": [
           *             {
           *               "boost_value": 0,
           *               "is_available": false,
           *               "predicted_final_value": 20,
           *               "movement_probability": "Stay"
           *             },
           *             {
           *               "boost_value": 1,
           *               "is_available": true,
           *               "predicted_final_value": 22,
           *               "movement_probability": "MoveUp"
           *             }
           *           ]
           *         },
           *         "boost_usage_history": [
           *           {
           *             "lap_number": 1,
           *             "boost_value": 2,
           *             "cycle_number": 1,
           *             "cards_remaining_after": 3,
           *             "replenishment_occurred": false
           *           },
           *           {
           *             "lap_number": 2,
           *             "boost_value": 0,
           *             "cycle_number": 1,
           *             "cards_remaining_after": 2,
           *             "replenishment_occurred": false
           *           }
           *         ],
           *         "boost_cycle_summaries": [
           *           {
           *             "cycle_number": 1,
           *             "cards_used": [
           *               2,
           *               0,
           *               3
           *             ],
           *             "laps_in_cycle": [
           *               1,
           *               2,
           *               3
           *             ],
           *             "average_boost": 1.67
           *           }
           *         ]
           *       }
           *     }
           */
          'application/json': components['schemas']['DetailedRaceStatusResponse'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  process_turn: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProcessLapRequest'];
      };
    };
    responses: {
      /** @description Lap processed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LapResultResponse'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot process turn */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_turn_phase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Turn phase information retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "turn_phase": "WaitingForPlayers",
           *       "current_lap": 2,
           *       "lap_characteristic": "Straight",
           *       "submitted_players": [
           *         "550e8400-e29b-41d4-a716-446655440000",
           *         "550e8400-e29b-41d4-a716-446655440001"
           *       ],
           *       "pending_players": [
           *         "550e8400-e29b-41d4-a716-446655440002"
           *       ],
           *       "total_active_players": 3
           *     }
           */
          'application/json': components['schemas']['TurnPhaseResponse'];
        };
      };
      /** @description Invalid UUID format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "INVALID_UUID",
           *       "message": "Invalid UUID format",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Race not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "RACE_NOT_FOUND",
           *       "message": "Race not found",
           *       "details": null
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "error": "DATABASE_ERROR",
           *       "message": "Internal server error",
           *       "details": "Failed to fetch race: connection timeout"
           *     }
           */
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  login_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCredentials'];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  register_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserRegistration'];
      };
    };
    responses: {
      /** @description User registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description User already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  health_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  submit_turn_action: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Race UUID */
        race_uuid: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitTurnActionRequest'];
      };
    };
    responses: {
      /** @description Action submitted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmitTurnActionResponse'];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Race or player not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action already submitted or race not in progress */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
